name: 'Check Changelog for changes'
description: 'Make sure that a PR also reflects in a change in the changelog'
branding:
  icon: 'hash'
  color: 'blue'
runs:
  using: "composite"
  steps:
  - name: Check out repository code
    uses: actions/checkout@v2
    with:
      fetch-depth: 0
  - name: Check for changes in changelog
    env:
      BASE_REF: ${{ github.event.pull_request.base.ref }}
      NO_CHANGELOG_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}
    run: ${{ github.action_path }}/check.sh
    shell: bash
